name: Deploy MkDocs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocstrings[python]
          
      - name: Deploy documentation
        run: |
          cd docs
          mkdocs gh-deploy --force --clean --verbose 